# -*- coding: utf-8 -*-
"""AQUACONSIENCE_modelo_isolation_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLhcZbFHCpNg3g7SIWzjyDLxVeELjUu3

# AQUACONSIENCE Isolation Forest

Objetivo: medir el agua que usan los hogares bogotanos y con un modelo de Machine Learning, generar alertas, estadísticas y recomendaciones que ayuden a crear hábitos de ahorro.

Dos modelos, según lo que el sensor logre medir:

- Modelo A (general): solo litros totales del hogar por día.
- Modelo B (actividades): litros por actividad (aseo personal, cocina, inodoro, lavado de ropa, limpieza).

Ambos normalizan por número de personas y comparan cada hogar contra su propio historial.

## 1. Librerías y carga de datos
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.metrics import roc_auc_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold

SEMILLA = 42
CONTAMINACION = 0.03   # proporción esperada de días anómalos
plt.rcParams["figure.figsize"] = (9, 4)

# Carga de los 3 Cvs
import io
try:
    from google.colab import files
    subidos = files.upload()
    leer = lambda clave: next(io.BytesIO(v) for k, v in subidos.items() if clave in k)
except ImportError:
    RUTA = "/mnt/user-data/uploads/"
    import glob
    leer = lambda clave: glob.glob(f"{RUTA}*{clave}*.csv")[0]

g = pd.read_csv(leer("consumo_general"), parse_dates=["fecha"]).sort_values(["hogar_id", "fecha"]).reset_index(drop=True)
a = pd.read_csv(leer("consumo_actividades"), parse_dates=["fecha"])
h = pd.read_excel(leer("hogares"))
print(g.shape, a.shape, h.shape)
g.head()

"""## 2. Exploración rápida de los datos"""

fig, ax = plt.subplots(1, 2, figsize=(12, 4))
g.groupby("personas")["litros_consumidos"].mean().plot.bar(ax=ax[0], color="#2E86C1")
ax[0].set_title("Litros por día según # de personas"); ax[0].set_ylabel("Litros/día")
g.groupby("personas")["litros_por_persona"].mean().plot.bar(ax=ax[1], color="#28B463")
ax[1].set_title("Litros por PERSONA al día"); ax[1].set_ylabel("Litros/persona/día")
plt.tight_layout(); plt.show()
print("Promedio hogares de 4 personas:", round(g[g.personas == 4].litros_consumidos.mean()), "L/día (referencia EAAB: ~396)")

# Las anomalías, consumo por persona
g.boxplot(column="litros_por_persona", by="es_anomalia_sintetica", grid=False)
plt.suptitle(""); plt.title("Litros por persona: normal (0) vs anomalía sintética (1)"); plt.show()

# Consumo promedio por actividad (litros por persona)
a.groupby("categoria")["litros_por_persona"].mean().sort_values().plot.barh(color="#2E86C1")
plt.title("Consumo promedio por actividad (L/persona/día)"); plt.show()

"""## 3. Modelo A - Consumo general

Variables: litros por persona, ratio frente al promedio de los 7 días anteriores del hogar, cambio frente a ayer y fin de semana.
El promedio de 7 días no incluye el día evaluado, así que no hay fuga de datos.
"""

def features_general(g):
    d = g.copy()
    d["ratio_vs_promedio"] = (d["litros_consumidos"] / d["promedio_7_dias"]).fillna(1.0)
    d["sin_historial"] = d["promedio_7_dias"].isna().astype(int)   # primera semana del hogar
    d["cambio_vs_dia_anterior_pct"] = d["cambio_vs_dia_anterior_pct"].fillna(0.0)
    d["fin_de_semana"] = d["fecha"].dt.dayofweek.isin([5, 6]).astype(int)
    return d

COLS_A = ["litros_por_persona", "ratio_vs_promedio", "cambio_vs_dia_anterior_pct", "fin_de_semana"]
dg = features_general(g)

def nuevo_modelo():
    return IsolationForest(n_estimators=300, contamination=CONTAMINACION, random_state=SEMILLA, n_jobs=-1)

# Evaluación entrenar con el pasado (hasta el 10-mar) y probar con el futuro
corte = pd.Timestamp("2026-03-11")
tr, te = dg[dg.fecha < corte], dg[dg.fecha >= corte]
m_eval = nuevo_modelo().fit(tr[COLS_A])
puntaje = -m_eval.decision_function(te[COLS_A])
pred = (m_eval.predict(te[COLS_A]) == -1).astype(int)
y = te["es_anomalia_sintetica"]
print(f"ROC-AUC:   {roc_auc_score(y, puntaje):.3f}")
print(f"Precisión: {precision_score(y, pred):.3f}")
print(f"Recall:    {recall_score(y, pred):.3f}")
print("Matriz de confusión (filas=real, cols=predicho):\n", confusion_matrix(y, pred))

# Modelo final A: entrenado con todos los datos
modelo_a = nuevo_modelo().fit(dg[COLS_A])
dg["puntaje_anomalia"] = -modelo_a.decision_function(dg[COLS_A])
dg["es_anomalia_predicha"] = (modelo_a.predict(dg[COLS_A]) == -1).astype(int)

# Visualiza un hogar
hid = "H001"
x = dg[dg.hogar_id == hid]
plt.plot(x.fecha, x.litros_consumidos, label="Consumo diario", color="#2E86C1")
plt.scatter(x[x.es_anomalia_predicha == 1].fecha, x[x.es_anomalia_predicha == 1].litros_consumidos,
            color="red", zorder=3, label="Anomalía detectada")
plt.title(f"Hogar {hid} — consumo diario y anomalías"); plt.ylabel("Litros"); plt.legend(); plt.show()

"""## 4. Modelo B - Consumo por actividad

Una fila por hogar-día con los litros por persona de cada actividad. Con solo 1000 hogar-días se usa validación cruzada de 5 folds.
"""

CATEGORIAS = ["aseo_personal", "cocina", "inodoro", "lavado_ropa", "limpieza_vivienda"]

def features_actividades(a):
    p = a.pivot_table(index=["hogar_id", "fecha", "personas"], columns="categoria", values="litros_por_persona").reset_index()
    p["total_lpp"] = p[CATEGORIAS].sum(axis=1)
    p["fin_de_semana"] = p["fecha"].dt.dayofweek.isin([5, 6]).astype(int)
    y = a.groupby(["hogar_id", "fecha"])["es_anomalia_sintetica"].max().rename("es_anomalia").reset_index()
    return p.merge(y, on=["hogar_id", "fecha"])

COLS_B = CATEGORIAS + ["total_lpp", "fin_de_semana"]
db = features_actividades(a)

filas = []
for tr_i, te_i in StratifiedKFold(5, shuffle=True, random_state=SEMILLA).split(db[COLS_B], db["es_anomalia"]):
    m = nuevo_modelo().fit(db.iloc[tr_i][COLS_B])
    yt = db.iloc[te_i]["es_anomalia"]
    pr = (m.predict(db.iloc[te_i][COLS_B]) == -1).astype(int)
    filas.append([roc_auc_score(yt, -m.decision_function(db.iloc[te_i][COLS_B])),
                  precision_score(yt, pr, zero_division=0), recall_score(yt, pr)])
print(pd.DataFrame(filas, columns=["ROC-AUC", "Precisión", "Recall"]).mean().round(3))

modelo_b = nuevo_modelo().fit(db[COLS_B])
db["puntaje_anomalia"] = -modelo_b.decision_function(db[COLS_B])
db["es_anomalia_predicha"] = (modelo_b.predict(db[COLS_B]) == -1).astype(int)

"""## 5. Alertas y recomendaciones

Isolation Forest detecta el día raro; las recomendaciones salen de reglas y textos definidos por CONSEJOS.
"""

CONSEJOS = {
    "aseo_personal": "Baños más cortos, cierra la llave al enjabonarte y al cepillarte los dientes. Revisa que la ducha no gotee.",
    "cocina": "Lava los platos con la llave cerrada mientras enjabonas, descongela sin agua corriente y reutiliza el agua de lavar verduras para las plantas.",
    "inodoro": "Un consumo alto aquí suele ser una FUGA en el tanque. Echa colorante en el tanque: si aparece en la taza sin descargar, hay fuga.",
    "lavado_ropa": "Lava solo con carga completa y usa el ciclo de ahorro de agua.",
    "limpieza_vivienda": "Usa balde en vez de manguera para pisos, patios y lavado del carro.",
    "general": "Revisa llaves, tanques y mangueras en busca de fugas y verifica si hubo visitas o actividades fuera de lo normal en casa.",
}

def alerta_general(f):
    txt = f"OJO: el {f['fecha']:%d/%m} usaste {f['litros_consumidos']:.0f} litros"
    if f["personas"] > 1:
        txt += f" ({f['litros_por_persona']:.0f} L por persona)"
    txt += ". "
    if f["sin_historial"] == 0:
        txt += f"Tu promedio de la semana anterior era {f['promedio_7_dias']:.0f} L, o sea {100*(f['ratio_vs_promedio']-1):+.0f} %. "
    return txt, CONSEJOS["general"]

def alerta_actividades(f, base):
    z = {}
    for c in CATEGORIAS:
        med = base[c].median()
        mad = (base[c] - med).abs().median() * 1.4826 or 1e-9
        z[c] = (f[c] - med) / mad
    peor = max(z, key=z.get)
    txt = (f"OJO: el {f['fecha']:%d/%m} el mayor exceso estuvo en {peor.replace('_', ' ')}: "
           f"{f[peor]:.0f} L por persona, cuando lo típico es {base[peor].median():.0f} L.")
    return txt, CONSEJOS[peor]

print("----------Modelo A---------")
for _, f in dg[dg.es_anomalia_predicha == 1].sort_values("puntaje_anomalia", ascending=False).head(3).iterrows():
    t, r = alerta_general(f); print(f"[{f.hogar_id}] {t}\n   → {r}\n")

print("-------Modelo B-------")
for _, f in db[db.es_anomalia_predicha == 1].sort_values("puntaje_anomalia", ascending=False).head(3).iterrows():
    t, r = alerta_actividades(f, db); print(f"[{f.hogar_id}] {t}\n   → {r}\n")

"""## 6. Estadísticas semanales por hogar"""

def estadisticas_semanales(g, hogar_id):
    x = g[g.hogar_id == hogar_id].sort_values("fecha")
    fin = x["fecha"].max()
    sem = x[x.fecha > fin - pd.Timedelta(days=7)]
    ant = x[(x.fecha <= fin - pd.Timedelta(days=7)) & (x.fecha > fin - pd.Timedelta(days=14))]
    personas = int(x["personas"].iloc[0])
    pares = g[(g.personas == personas) & (g.hogar_id != hogar_id) & (g.fecha > fin - pd.Timedelta(days=7))]
    out = {
        "hogar": hogar_id, "personas": personas,
        "litros_semana": round(sem.litros_consumidos.sum()),
        "litros_por_persona_dia": float(round(sem.litros_por_persona.mean(), 1)),
        "dia_de_mayor_consumo": sem.loc[sem.litros_consumidos.idxmax(), "fecha"].strftime("%d/%m"),
    }
    if len(ant):
        out["cambio_vs_semana_anterior_pct"] = float(round(100 * (sem.litros_consumidos.sum() / ant.litros_consumidos.sum() - 1), 1))
    if len(pares):
        out["promedio_hogares_similares_L_pp"] = float(round(pares.litros_por_persona.mean(), 1))
    return out

estadisticas_semanales(g, "H001")

"""## 7. Guardar los modelos"""

import joblib
joblib.dump({"modelo": modelo_a, "columnas": COLS_A}, "modelo_A_general.joblib")
joblib.dump({"modelo": modelo_b, "columnas": COLS_B}, "modelo_B_actividades.joblib")
try:
    files.download("modelo_A_general.joblib"); files.download("modelo_B_actividades.joblib")
except NameError:
    pass